import { Achievement, UserProgress } from './types';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_code',
    title: 'Primeiro Código!',
    titleEn: 'First Code!',
    description: 'Executou seu primeiro código Python',
    descriptionEn: 'Ran your first Python code',
    icon: '🎉',
    condition: (p: UserProgress) => p.completedExercises.length >= 1,
    xpReward: 50,
  },
  {
    id: 'first_lesson',
    title: 'Primeira Aula',
    titleEn: 'First Lesson',
    description: 'Completou sua primeira aula',
    descriptionEn: 'Completed your first lesson',
    icon: '📖',
    condition: (p: UserProgress) => p.completedLessons.length >= 1,
    xpReward: 30,
  },
  {
    id: 'streak_3',
    title: 'Dedicado',
    titleEn: 'Dedicated',
    description: '3 dias seguidos estudando',
    descriptionEn: '3 days studying in a row',
    icon: '🔥',
    condition: (p: UserProgress) => p.streak >= 3,
    xpReward: 100,
  },
  {
    id: 'streak_7',
    title: 'Maratonista',
    titleEn: 'Marathoner',
    description: '7 dias seguidos estudando',
    descriptionEn: '7 days studying in a row',
    icon: '🏃',
    condition: (p: UserProgress) => p.streak >= 7,
    xpReward: 300,
  },
  {
    id: 'streak_30',
    title: 'Imparável',
    titleEn: 'Unstoppable',
    description: '30 dias seguidos estudando',
    descriptionEn: '30 days studying in a row',
    icon: '⚡',
    condition: (p: UserProgress) => p.streak >= 30,
    xpReward: 1000,
  },
  {
    id: 'xp_500',
    title: 'Acumulador',
    titleEn: 'Accumulator',
    description: 'Alcançou 500 XP',
    descriptionEn: 'Reached 500 XP',
    icon: '⭐',
    condition: (p: UserProgress) => p.xp >= 500,
    xpReward: 50,
  },
  {
    id: 'xp_2000',
    title: 'Experiente',
    titleEn: 'Experienced',
    description: 'Alcançou 2000 XP',
    descriptionEn: 'Reached 2000 XP',
    icon: '🌟',
    condition: (p: UserProgress) => p.xp >= 2000,
    xpReward: 100,
  },
  {
    id: 'level_3',
    title: 'Desenvolvedor',
    titleEn: 'Developer',
    description: 'Atingiu o nível Desenvolvedor',
    descriptionEn: 'Reached Developer level',
    icon: '💻',
    condition: (p: UserProgress) => p.level >= 3,
    xpReward: 150,
  },
  {
    id: 'exercises_10',
    title: 'Praticante',
    titleEn: 'Practitioner',
    description: 'Completou 10 exercícios',
    descriptionEn: 'Completed 10 exercises',
    icon: '🏋️',
    condition: (p: UserProgress) => p.completedExercises.length >= 10,
    xpReward: 100,
  },
  {
    id: 'exercises_50',
    title: 'Veterano',
    titleEn: 'Veteran',
    description: 'Completou 50 exercícios',
    descriptionEn: 'Completed 50 exercises',
    icon: '🎖️',
    condition: (p: UserProgress) => p.completedExercises.length >= 50,
    xpReward: 500,
  },
  {
    id: 'lessons_10',
    title: 'Estudioso',
    titleEn: 'Studious',
    description: 'Completou 10 aulas',
    descriptionEn: 'Completed 10 lessons',
    icon: '🎓',
    condition: (p: UserProgress) => p.completedLessons.length >= 10,
    xpReward: 200,
  },
  {
    id: 'perfect_quiz',
    title: 'Perfeccionista',
    titleEn: 'Perfectionist',
    description: 'Tirou 100% em um quiz',
    descriptionEn: 'Got 100% on a quiz',
    icon: '💯',
    condition: (p: UserProgress) => Object.values(p.quizScores).some(s => s === 100),
    xpReward: 150,
  },
  {
    id: 'study_hour',
    title: 'Uma Hora de Código',
    titleEn: 'One Hour of Code',
    description: 'Estudou por 1 hora no total',
    descriptionEn: 'Studied for 1 hour total',
    icon: '⏰',
    condition: (p: UserProgress) => p.totalStudyMinutes >= 60,
    xpReward: 100,
  },
  {
    id: 'pythonista',
    title: 'Pythonista',
    titleEn: 'Pythonista',
    description: 'Completou todos os módulos de Python',
    descriptionEn: 'Completed all Python modules',
    icon: '🐍',
    condition: (p: UserProgress) => p.completedLessons.length >= 40,
    xpReward: 500,
  },
  {
    id: 'placement_test',
    title: 'Bússola de Conhecimento',
    titleEn: 'Knowledge Compass',
    description: 'Concluiu o teste de nivelamento',
    descriptionEn: 'Completed the placement test',
    icon: '🧭',
    condition: (p: UserProgress) => Boolean(p.placementCompleted),
    xpReward: 100,
  },
];
